// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClOp08CKFpqfChg9ipuAdLrr2o_bnPa-M',
    appId: '1:614983544631:android:b31d352bd044a5a95934b2',
    messagingSenderId: '614983544631',
    projectId: 'lockin-app-jasgida',
    storageBucket: 'lockin-app-jasgida.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbBLLy2B9WYiurQkGqE3JSumvwj71WaR0',
    appId: '1:614983544631:ios:4b71b2bf39a1020c5934b2',
    messagingSenderId: '614983544631',
    projectId: 'lockin-app-jasgida',
    storageBucket: 'lockin-app-jasgida.firebasestorage.app',
    iosBundleId: 'com.example.lockinApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcykOEl89Sx9yFruq9qA6Pzqqr-t8xuCk',
    appId: '1:614983544631:web:f89ce89441e7ee495934b2',
    messagingSenderId: '614983544631',
    projectId: 'lockin-app-jasgida',
    authDomain: 'lockin-app-jasgida.firebaseapp.com',
    storageBucket: 'lockin-app-jasgida.firebasestorage.app',
    measurementId: 'G-2RLZMNHGET',
  );

}